#!/usr/bin/env bash
# scripts/secrets-push.sh
#
# Pushes secrets to VM.
#
# Traefik auth → ~/traefik/config/auth.yml  (credentials only)
# Seafile      → ~/seafile/.env
#
# dynamic.yml (non-secret traefik config) is handled by vm-sync.
# auth.yml and dynamic.yml are separate files — they never conflict.
# Traefik loads all .yml files in config/ automatically.
#
# USAGE:
#   ./scripts/secrets-push.sh           push all
#   ./scripts/secrets-push.sh traefik   push only traefik auth
#   ./scripts/secrets-push.sh seafile   push only seafile .env

set -euo pipefail

ENV_FILE="$(git rev-parse --show-toplevel)/.env.local"
[ -f "$ENV_FILE" ] || { echo "ERROR: .env.local not found."; exit 1; }
set -a; source "$ENV_FILE"; set +a

SSH_CMD="ssh -p ${VM_PORT} ${VM_USER}@${VM_HOST}"
SCP_CMD="scp -P ${VM_PORT}"
TARGET="${1:-all}"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${BLUE}[→]${NC} $1"; }
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

# ── Traefik ───────────────────────────────────────────────────────
# Writes auth.yml with dashboard credentials ONLY.
# Uses Python to write the file — avoids all shell/heredoc dollar-sign
# corruption issues that mangled the htpasswd hash previously.
push_traefik() {
    log "Pushing Traefik credentials to ~/traefik/config/auth.yml..."

    local tmp
    tmp=$(mktemp /tmp/auth_XXXXXX.yml)

    # Python writes the file directly — no shell escaping of $ signs
    TRAEFIK_DASHBOARD_PASSWORD_HASH="$TRAEFIK_DASHBOARD_PASSWORD_HASH" \
    python3 -c "
import os, sys

pw_hash = os.environ['TRAEFIK_DASHBOARD_PASSWORD_HASH']

# In YAML files Traefik reads directly, write hash with literal $ signs.
# $$ escaping is only for Docker Compose labels/env vars, not YAML files.

content = '''# ~/traefik/config/auth.yml
# AUTO-GENERATED by secrets-push.sh
# Edit .env.local and run: make secrets-push-traefik
# Non-secret config is in dynamic.yml (uploaded by vm-sync)

http:
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - \"{pw}\"
        realm: \"sushantgupta.cloud\"
'''.format(pw=pw_hash)

with open(sys.argv[1], 'w') as f:
    f.write(content)
" "$tmp"

    $SSH_CMD 'mkdir -p ~/traefik/config'
    $SCP_CMD "$tmp" "${VM_USER}@${VM_HOST}:~/traefik/config/auth.yml"
    rm "$tmp"
    $SSH_CMD 'chmod 600 ~/traefik/config/auth.yml'
    ok "Traefik auth.yml pushed — Traefik hot-reloads automatically"
}

# ── Seafile ───────────────────────────────────────────────────────
push_seafile() {
    log "Pushing Seafile .env to VM..."

    local tmp
    tmp=$(mktemp /tmp/seafile_XXXXXX.env)
    cat > "$tmp" << EOF
# ~/seafile/.env — AUTO-GENERATED by secrets-push.sh
DB_ROOT_PASSWORD=${SEAFILE_DB_ROOT_PASSWORD}
SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
EOF

    $SCP_CMD "$tmp" "${VM_USER}@${VM_HOST}:~/seafile/.env"
    rm "$tmp"
    $SSH_CMD 'chmod 600 ~/seafile/.env'
    ok "Seafile .env pushed → ~/seafile/.env"
}

# ── Umami ─────────────────────────────────────────────────────────
push_umami() {
    log "Pushing Umami .env to VM..."
    $SSH_CMD 'mkdir -p ~/analytics'

    local tmp
    tmp=$(mktemp /tmp/umami_XXXXXX.env)
    cat > "$tmp" << EOF
# ~/analytics/.env — AUTO-GENERATED by secrets-push.sh
DATABASE_PASSWORD=${UMAMI_DB_PASSWORD}
APP_SECRET=${UMAMI_APP_SECRET}
EOF

    $SCP_CMD "$tmp" "${VM_USER}@${VM_HOST}:~/analytics/.env"
    rm "$tmp"
    $SSH_CMD 'chmod 600 ~/analytics/.env'
    ok "Umami .env pushed → ~/analytics/.env"
}

# ── Dashboard ─────────────────────────────────────────────────────
push_dashboard() {
    log "Pushing Portainer .env to VM..."
    $SSH_CMD 'mkdir -p ~/dashboard'

    local tmp
    tmp=$(mktemp /tmp/dashboard_XXXXXX.env)
    cat > "$tmp" << EOF
# ~/dashboard/.env — AUTO-GENERATED by secrets-push.sh
PORTAINER_ADMIN_PASSWORD=${PORTAINER_ADMIN_PASSWORD}
EOF

    $SCP_CMD "$tmp" "${VM_USER}@${VM_HOST}:~/dashboard/.env"
    rm "$tmp"
    $SSH_CMD 'chmod 600 ~/dashboard/.env'
    ok "Dashboard .env pushed → ~/dashboard/.env"
}

# ── Dispatch ──────────────────────────────────────────────────────
echo ""
log "Pushing secrets to ${VM_USER}@${VM_HOST}..."
echo ""

case "$TARGET" in
    traefik)   push_traefik ;;
    seafile)   push_seafile ;;
    umami)     push_umami ;;
    dashboard) push_dashboard ;;
    all)
        push_traefik
        push_seafile
        $SSH_CMD 'test -d ~/analytics' 2>/dev/null && push_umami \
            || warn "Skipping umami — ~/analytics not on VM yet"
        $SSH_CMD 'test -d ~/dashboard' 2>/dev/null && push_dashboard \
            || warn "Skipping dashboard — ~/dashboard not on VM yet"
        ;;
    *)
        echo "Unknown service: $TARGET"
        echo "Usage: $0 [traefik|seafile|umami|dashboard|all]"
        exit 1
        ;;
esac

echo ""
ok "Done."
echo ""
echo "If you updated Seafile credentials: make seafile-restart"